### PR TITLE
style: add a custom AdonisJS theme for scalar

### PR DESCRIPTION
**Pull request by hanspagel**
This PR adds a custom theme matching the AdonisJS colors and styles for the Scalar API reference added in #54. ✨ 

https://github.com/ad-on-is/adonis-autoswagger/assets/1577992/b15ce599-d00c-4376-916e-b75f64cb8039

To be honest, I added this blindly. What’s the best/quickest way for me to test the source in a real project? 👀

### CODE REVIEW

**Comment by ad-on-is** [comment]
I need to think about this one, but I'd rather not have additional CSS and stuff in the package, since I think this would be better off done in the adonisjs project itself.

**Comment by ad-on-is** [comment]
Done in 2.12

**Comment by ad-on-is** [comment]
autoswagger-peek

**Comment by hanspagel** [comment]
That was fast. :)

**Pull request merged**
