### PR TITLE
add @required parser model

### PR DESCRIPTION
**Pull request by pdipax**

### CODE REVIEW

**Comment by pdipax** [comment]
Hi, can I kindly ask you for feedback from the PR? Because for us it is essential to use @required and with this simple modification it is integrated. If it is not possible to merge we should work directly on our fork with the possibility in the future of not being able to support the project if we distance ourselves from the code. I look forward to hearing from you and in the meantime I thank you

**Comment by ad-on-is** [comment]
> with the possibility in the future of not being able to support the project if we distance ourselves from the code
Dude, are you for real? Did you consider that I might just not have had the time/energy to test and merge your PR, or that I might've been sick? You can't just pass the pressure of your boss/clients onto someone else in the FOSS community.

>  If it is not possible to merge we should work directly on our fork
Feel free to do so. It's MIT and you can fork it if you think that 3 days is a long time to wait for a PR to be merged.

Sometimes it takes some time, other times I implement stuff within a day or two.

**Comment by ad-on-is** [comment]
Well... looks like we'll have to wait, until NPM fixes a bug. I cannot publish to NPM right now.
https://github.com/orgs/community/discussions/124854

**Comment by pdipax** [comment]
I'm sorry you took it out on yourself. I always thank and appreciate your work, in fact I want to contribute to the development of the module. Thanks

**Comment by ad-on-is** [comment]
Fixed in 3.27.0

**Pull request merged**
