### PR TITLE
Support adonis v6

### PR DESCRIPTION
**Pull request by Ziut3k-dev**

### CODE REVIEW

**Comment by Ziut3k-dev** [comment]
- [ ] resolve all methods from new adonis

**Comment by ad-on-is** [comment]
@Ziut3k-dev I haven't had a chance to trye adonisjs v6 yet, but **will this still work with adonisjs v5?**

**Comment by Ziut3k-dev** [comment]
@ad-on-is with v5 this branch not working, Adonis fully rework type of routes in v6

**Comment by ad-on-is** [comment]
> @ad-on-is with v5 this branch not working, Adonis fully rework type of routes in v6

This is not good, backward-compatibility with v5 MUST be assured.

Is there no such thing as `Route.toJSON()` in v6, so the routes get passed to adonis-autoswagger, which are then handled converted to the already existing interface?

**Comment by Ziut3k-dev** [comment]
> > @ad-on-is with v5 this branch not working, Adonis fully rework type of routes in v6
> 
> This is not good, backward-compatibility with v5 MUST be assured.
> 
> Is there no such thing as `Route.toJSON()` in v6, so the routes get passed to adonis-autoswagger, which are then converted to the already existing interfaces like `AdonisRoute` and ` AdoniseRouteMeta`?

I haven't had time to try to convert it to the interface with v5 yet, by the end of the week I will sit down and test what and how

**Comment by zecar** [comment]
@Ziut3k-dev do you plan to handle this in the near future? Not to put any pressure but I am in need of this package on v6 or I will have to research alternatives :(

**Comment by ad-on-is** [comment]
> @Ziut3k-dev do you plan to handle this in the near future? Not to put any pressure but I am in need of this package on v6 or I will have to research alternatives :(

I have some spare time and will look into it myself these days.

**Comment by ad-on-is** [comment]
v6 compatibility and v5 backwards-compatibility are now implemented in v 2.0.0

**Pull request closed without merging**
