### PR TITLE
feat: allow to add a @operationId comment

### PR DESCRIPTION
**Pull request by MuaDDuB**
Hi there, 

Really fan of this lib, and I would like to contribute my two cents.

I've added the ability to add a `@operationId` comment that will be added to the openAPI spec. 

Tell me if I can do more 😄

### CODE REVIEW

**Comment by MuaDDuB** [comment]
Sometimes, we like to have an operationId declared manually. 
But I've added some code to reuse the route handler so that the operationId is in form controllerNameMethodName.

OperationId should be in camelCase : https://swagger.io/docs/specification/2-0/paths-and-operations/#:~:text=Describing%20Parameters.-,operationId,-Each%20operation%20may

**Comment by MuaDDuB** [comment]
I've also added some TS interfaces to help develop this lib 😄

**Comment by ad-on-is** [comment]
> I've also added some TS interfaces to help develop this lib 😄

Yeah, the code is a mess, but I was also in a rush when writing it 😂

**Comment by MuaDDuB** [comment]
> > I've also added some TS interfaces to help develop this lib 😄
> 
> Yeah, the code is a mess, but I was also in a rush when writing it 😂

Héhé, it is not an issue for me, thx for at least starting this initiative, it's beneficial, and if I can help add some features, everyone will be happy 😄 


I'll let you merge this PR if it's okay for you 😸

**Pull request merged**
